import { Check, Copy, Eye, ExternalLink, Loader2, Pencil, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { ScrollArea } from "@/components/ui/scroll-area";
import { editarRegistro, excluirRegistro, useRelmeg } from "@/lib/relmeg/store";
import { briefing, cellText, isUrl, recordTitle } from "@/lib/relmeg/types";
export function DetailPanel({ recordId, onClose, editarAoAbrir=false }: { recordId: string | null; onClose: () => void; editarAoAbrir?: boolean }) { const { data, dataset, sincronizando } = useRelmeg(); const record = data.find((r) => r.id === recordId); const columns = dataset?.columns ?? []; const [editing,setEditing]=useState(editarAoAbrir); const [copied,setCopied]=useState(false); useEffect(()=>{ if(recordId)setEditing(editarAoAbrir)},[recordId,editarAoAbrir]); if(!dataset) return null; const copy=async()=>{if(!record)return; await navigator.clipboard.writeText(briefing(record,columns));setCopied(true);toast.success("Resumo copiado");setTimeout(()=>setCopied(false),1600)}; return <Sheet open={Boolean(record)} onOpenChange={(v)=>{if(!v)onClose()}}><SheetContent className="w-full gap-0 border-border bg-card p-0 sm:max-w-xl">{record&&<><SheetHeader className="border-b border-border p-4 sm:p-6"><SheetTitle className="font-display text-xl">{recordTitle(record,columns)}</SheetTitle><div className="flex flex-wrap gap-2 pt-3"><Button size="sm" variant="outline" onClick={()=>setEditing(!editing)}>{editing?<Eye/>:<Pencil/>}{editing?"Visualizar":"Editar"}</Button><Button size="sm" variant="outline" className="text-destructive" onClick={async()=>{await excluirRegistro(record.id);onClose();toast.success("Registro excluído")}}><Trash2/>Excluir</Button>{sincronizando&&<span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><Loader2 className="animate-spin"/>salvando…</span>}</div></SheetHeader><ScrollArea className="h-[calc(100dvh-12rem)]"><div className="space-y-4 p-4 sm:p-6">{columns.map((c)=>{const value=cellText(record.data[c.key]);return <section key={c.key} className="space-y-1.5"><Label htmlFor={`${record.id}-${c.key}`} className="text-xs text-muted-foreground">{c.label}</Label>{editing?(c.type==="text"&&value.length>100?<Textarea id={`${record.id}-${c.key}`} className="min-h-24" value={value} onChange={(e)=>editarRegistro(record.id,c.key,e.target.value)}/>:<Input id={`${record.id}-${c.key}`} type={c.type==="number"?"number":"text"} value={value} onChange={(e)=>editarRegistro(record.id,c.key,c.type==="number"?(e.target.value===""?null:Number(e.target.value)):e.target.value)}/>):isUrl(value)?<a href={value} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 break-all text-sm text-primary hover:underline">{value}<ExternalLink className="h-3 w-3"/></a>:<p className="whitespace-pre-wrap break-words text-sm text-foreground">{value||"—"}</p>}</section>})}</div></ScrollArea><div className="border-t border-border p-4"><Button className="w-full" onClick={copy}>{copied?<Check/>:<Copy/>}Copiar resumo</Button></div></>}</SheetContent></Sheet> }
