import { Search, FilterX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { clearFilters, setFilter, useRelmeg } from "@/lib/relmeg/store";
import { cellText, type DataColumn, type DataRecord, type Filters } from "@/lib/relmeg/types";
const ALL = "__all__";
export function aplicarFiltros(data: DataRecord[], filters: Filters) { const q = filters.busca.trim().toLowerCase(); return data.filter((r) => { if (q && !Object.values(r.data).map(cellText).join(" ").toLowerCase().includes(q)) return false; return Object.entries(filters.campos).every(([key, value]) => !value || cellText(r.data[key]) === value); }); }
export function FilterBar({ data, columns }: { data: DataRecord[]; columns: DataColumn[] }) { const { filters } = useRelmeg(); const filterable = columns.filter((c) => new Set(data.map((r) => cellText(r.data[c.key])).filter(Boolean)).size <= 30).slice(0, 6); const active = Number(Boolean(filters.busca)) + Object.values(filters.campos).filter(Boolean).length; return <div className="panel rounded-xl p-3"><div className="grid gap-2 sm:grid-cols-2 lg:flex lg:flex-wrap"><div className="relative min-w-0 flex-1 sm:col-span-2 lg:min-w-60"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={filters.busca} onChange={(e) => setFilter("busca", e.target.value)} placeholder="Buscar em todos os dados…" className="pl-9"/></div>{filterable.map((c) => { const values = [...new Set(data.map((r) => cellText(r.data[c.key])).filter(Boolean))].sort(); return <Select key={c.key} value={filters.campos[c.key] || ALL} onValueChange={(v) => setFilter(c.key, v === ALL ? "" : v)}><SelectTrigger className="w-full lg:w-44"><SelectValue placeholder={c.label}/></SelectTrigger><SelectContent><SelectItem value={ALL}>{c.label}: todos</SelectItem>{values.map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select> })}<Button variant="outline" onClick={clearFilters} disabled={!active}><FilterX className="h-4 w-4"/>Limpar Filtros{active ? ` (${active})` : ""}</Button></div></div>; }
