import { Search, FilterX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { clearFilters, setFilter, setPeriodo, setVisao, TODAS, useRelmeg } from "@/lib/relmeg/store";
import { cellText, type DataColumn, type DataRecord, type Filters } from "@/lib/relmeg/types";
const ALL = "__all__";
export { aplicarFiltros } from "@/lib/relmeg/engine";
export function FilterBar({ data, columns }: { data: DataRecord[]; columns: DataColumn[] }) { const { filters, bases, visao } = useRelmeg(); const filterable = columns.filter((c) => new Set(data.map((r) => cellText(r.data[c.key])).filter(Boolean)).size <= 30).slice(0, 6); const datas = columns.filter((c) => c.type === "date" || /(data|date)/i.test(c.label)); const active = Number(Boolean(filters.periodo?.de || filters.periodo?.ate)) + Number(Boolean(filters.busca)) + Object.values(filters.campos).filter(Boolean).length; return <div className="panel rounded-xl p-3"><div className="grid gap-2 sm:grid-cols-2 lg:flex lg:flex-wrap">{bases.length > 1 && <Select value={visao} onValueChange={setVisao}><SelectTrigger aria-label="Planilha" className="w-full lg:w-56"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={TODAS}>Todas as planilhas (cruzadas)</SelectItem>{bases.map((b) => <SelectItem key={b.id} value={b.id}>{b.name}</SelectItem>)}</SelectContent></Select>}<div className="relative min-w-0 flex-1 sm:col-span-2 lg:min-w-60"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={filters.busca} onChange={(e) => setFilter("busca", e.target.value)} placeholder="Buscar em todos os dados…" className="pl-9"/></div>{filterable.map((c) => { const values = [...new Set(data.map((r) => cellText(r.data[c.key])).filter(Boolean))].sort(); return <Select key={c.key} value={filters.campos[c.key] || ALL} onValueChange={(v) => setFilter(c.key, v === ALL ? "" : v)}><SelectTrigger className="w-full lg:w-44"><SelectValue placeholder={c.label}/></SelectTrigger><SelectContent><SelectItem value={ALL}>{c.label}: todos</SelectItem>{values.map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select> })}{datas.length>0&&<div className="flex flex-wrap items-center gap-2 sm:col-span-2 lg:col-span-1"><Select value={filters.periodo?.col||datas[0]!.key} onValueChange={(v)=>setPeriodo({col:v,de:filters.periodo?.de??"",ate:filters.periodo?.ate??""})}><SelectTrigger aria-label="Coluna de período" className="w-full sm:w-40"><SelectValue/></SelectTrigger><SelectContent>{datas.map(c=><SelectItem key={c.key} value={c.key}>{c.label}</SelectItem>)}</SelectContent></Select><Input type="date" aria-label="De" className="w-full sm:w-36" value={filters.periodo?.de??""} onChange={(e)=>setPeriodo({col:filters.periodo?.col||datas[0]!.key,de:e.target.value,ate:filters.periodo?.ate??""})}/><Input type="date" aria-label="Até" className="w-full sm:w-36" value={filters.periodo?.ate??""} onChange={(e)=>setPeriodo({col:filters.periodo?.col||datas[0]!.key,de:filters.periodo?.de??"",ate:e.target.value})}/></div>}<Button variant="outline" onClick={clearFilters} disabled={!active}><FilterX className="h-4 w-4"/>Limpar Filtros{active ? ` (${active})` : ""}</Button></div></div>; }
