/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as ApiAnaliseRouteImport } from './routes/api/analise'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnaliseRoute = ApiAnaliseRouteImport.update({
  id: '/api/analise',
  path: '/api/analise',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/analise': typeof AnaliseRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboards': typeof DashboardsRoute
  '/api/analise': typeof ApiAnaliseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/analise': typeof AnaliseRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboards': typeof DashboardsRoute
  '/api/analise': typeof ApiAnaliseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/analise': typeof AnaliseRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboards': typeof DashboardsRoute
  '/api/analise': typeof ApiAnaliseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/analise'
    | '/configuracoes'
    | '/dashboards'
    | '/api/analise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/analise'
    | '/configuracoes'
    | '/dashboards'
    | '/api/analise'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/analise'
    | '/configuracoes'
    | '/dashboards'
    | '/api/analise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  AnaliseRoute: typeof AnaliseRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardsRoute: typeof DashboardsRoute
  ApiAnaliseRoute: typeof ApiAnaliseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analise': {
      id: '/api/analise'
      path: '/api/analise'
      fullPath: '/api/analise'
      preLoaderRoute: typeof ApiAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  AnaliseRoute: AnaliseRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardsRoute: DashboardsRoute,
  ApiAnaliseRoute: ApiAnaliseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
